# Generated by Django 6.0.2 on 2026-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('boss_hp', models.IntegerField(default=120)),
                ('fase', models.IntegerField(default=1)),
                ('entropia', models.FloatField(default=0)),
                ('memoria', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
